version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - church-network
    depends_on:
      postgres:
        condition: service_healthy
    # Configuração para clonar o repositório
    command: sleep infinity

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: church_finance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - church-network
    ports:
      - "5432:5432"  # Adicione esta linha para expor a porta
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d church_finance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  church-network: